# Generated by Django 5.2.7 on 2025-10-06 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrating',
            name='total_games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userrating',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrating',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
